# Generated by claude
import os
from pathlib import Path

from dotenv import load_dotenv

# App's own config location — independent of whatever folder the user is indexing
CONFIG_DIR = Path.home() / ".config" / "ragctl"
ENV_FILE = CONFIG_DIR / "config.env"


def save_key(provider: str, api_key: str):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    env_var_name = f"{provider.upper()}_API_KEY"
    lines = []
    if ENV_FILE.exists():
        lines = ENV_FILE.read_text().splitlines()
    lines = [l for l in lines if not l.startswith(f"{env_var_name}=")]
    lines.append(f"{env_var_name}={api_key}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)


def get_api_key(provider: str) -> str | None:
    if ENV_FILE.exists():
        load_dotenv(ENV_FILE)
    return os.environ.get(f"{provider.upper()}_API_KEY")
